# This is a basic workflow to help you get started with Actions

name: ALM_CI_Utility_MACHANI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ALM_Test"
  ALM_Test:
    # The type of runner that the job will run on
    runs-on: OGE

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Change Dir and Exec ALM Test
        run: |
           echo 'cd /Users/raghavendra.x.machani.-nd/actions-runner/temp1'
           cd /Users/raghavendra.x.machani.-nd/actions-runner/temp2
           echo 'touch test1'
           touch test1
          # echo ':: CD C:\CI_Utility\ADM-FT-ToolsLauncher\bin\Debug'
          # CD C:\CI_Utility\ADM-FT-ToolsLauncher\bin\Debug
          # echo ':: .\FTToolsLauncher.exe -parmafile ALM_TestSet.mtd'
          # .\FTToolsLauncher.exe -parmafile ALM_TestSet.mtd
